title:        Jaison Erick
tagline:      'Personal Blog'
description:  'A blog about coding, tech and entrepreneurship'
url:          http://jaisonerick.github.io
version:      1.0
author:
  name:       'Jaison Erick'
  email:      'jaisonreis@gmail.com'
markdown:     rdiscount
permalink:    pretty
pygments:     true
paginate:     5
