# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Jaison Erick
tagline:      'Personal Blog'
description:  'A blog about coding, tech and entrepreneurship'
url:          http://jaisonerick.github.io
baseurl:          /

author:
  name:           'Jaison Erick'
  url:            https://twitter.com/jaisonerick

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/jaisonerick/jaisonerick.github.io
